inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

# クラスやモジュールにコメントを付与する制約をかけたくないため。
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 13

ClassLength:
  CountComments: false
  Max: 100

# RSpec/ContextWordingを無効
RSpec/ContextWording:
  Enabled: false

Style/HashSyntax:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false