source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.8"

# Use mysql as the database for Active Record
gem "mysql2", "~> 0.5"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder" # JSONを生成するのに使用する

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Github: https://github.com/ridgepole/ridgepole
gem 'ridgepole' # マイグレーションに使用するgem

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem "rack-cors"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"

  # Github: https://github.com/rubocop/rubocop
  gem 'rubocop', require: false
  # Github: https://github.com/rubocop/rubocop-performance
  gem "rubocop-performance", require: false
  # Github: https://github.com/rubocop/rubocop-rails
  gem "rubocop-rails", require: false
  # Github: https://github.com/rubocop/rubocop-rspec
  gem "rubocop-rspec", require: false

  # Github: https://github.com/ctran/annotate_models
  gem 'annotate' # 各モデルのスキーマ情報を書き出してくれる

  # Github: https://github.com/pry/pry-rails
  gem 'pry-rails' # Pryをデフォルトのコンソールとして使用できるようにする(Pryの機能をRailsコンソール内で利用することができる)
  # Github: https://github.com/deivid-rodriguez/pry-byebug
  gem 'pry-byebug' # binding.pryを使えるようにする
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]

  # Github: https://github.com/thoughtbot/factory_bot
  gem 'factory_bot_rails' # FactoryBotのgem

  # Github: https://github.com/rspec/rspec-rails
  gem 'rspec-rails' # RSpecのgem

  # Github: https://github.com/ruby-i18n/i18n
  gem 'rails-i18n' # i18n 日本語化対応用gem

  # Github: https://github.com/faker-ruby/faker
  gem 'faker' # ランダムなテストデータ生成に使用
end
