name: Frontend CI
on:
  pull_request:
    paths:
      - ".github/workflows/frontend_test.yml"
      - "frontend/**"

jobs:
  jest:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "./frontend/package.json"
          cache: "yarn"
          cache-dependency-path: "./frontend/yarn.lock.json"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Cache Jest
        uses: actions/cache@v4
        env:
          cache-name: cache-jest
        with:
          path: ./frontend/node_modules/.cache/jest
          key: ${{ runner.os }}-jest-${{ hashFiles('frontend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-jest-

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v2
        id: cpu-cores

      - name: Run test SP
        run: npx cross-env DEVICE=sp jest --bail --forceExit --max-workers ${{ steps.cpu-cores.outputs.count }}

      - name: Run test PC
        run: npx cross-env DEVICE=pc jest --bail --forceExit --max-workers ${{ steps.cpu-cores.outputs.count }}
